### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [RedTurtle/TurtledGazette#5]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by keul** [comment]
@karan licence file(s) are in the docs folder: https://github.com/RedTurtle/TurtledGazette/tree/master/docs

Isn't this enough? Let me know

**Comment by karan** [comment]
I'm not sure. But it's generally good practice to have license info in the root-level directory. You won't always ship the docs, and people can choose to delete the docs, but license info should never be. :)

**Comment by keul** [comment]
Commonly in the Python world you'll ship an egg using Python distutils. Deleting the "docs" folder will make `python setup.py sdist` to fail (so I think is enough).

**Comment by karan** [comment]
Ok. That should be fine. Thanks @keul
